### ISSUE TITLE
reward leak?

### ISSUE THREAD

**Issue by altonen** [mintlayer/pallet-utxo#11]
Hi,

I was reading through the implementation and found this weird piece of code [1].

The code seems to take the next reward from the storage and tries to split it fairly but if the split doesn't result in a positive value, the function exists early. That is, if the reward is 9 and there are 10 auths, the reward is not used but the documentation for `take()` [2] says that the value is removed afterwards. So isn't the reward leaked if it cannot be divided fairly or have I misunderstood something?

Furthermore, I don't understand why the code adds zero-valued rewards into the storage (if the remainder is zero) but that's another issue.

[1] https://github.com/mintlayer/pallet-utxo/blob/staging/src/lib.rs#L184
[2] https://substrate.dev/rustdocs/latest/frame_support/storage/trait.StorageValue.html#tymethod.take

**Comment by muursh** [comment]
Okay it's half correct. The general behaviour is correct in that we should exit early as we can't pay less than the smallest unit. 
The reward is leaked though. 
We need to handle it as if it's a remainder like here https://github.com/mintlayer/pallet-utxo/blob/master/src/lib.rs#L119
